envVarGroups:
  - name: shared-env
    envVars:
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: S3_BUCKET_NAME
        value: liefeed-images
      - key: SES_SENDER
        value: newsletter@liefeed.com
      - key: FACEBOOK_PAGE_ID
        value: "588785644323565"
      - key: FACEBOOK_PAGE_TOKEN
        sync: false
      - key: X_API_KEY
        sync: false
      - key: X_API_SECRET
        sync: false
      - key: X_BEARER_TOKEN
        sync: false
      - key: X_ACCESS_TOKEN
        sync: false
      - key: X_ACCESS_TOKEN_SECRET
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CONTACT_RECEIVER_EMAIL
        value: editor@liefeed.com
      - key: INBOUND_BUCKET_NAME
        value: liefeed-inbound-emails
      - key: INBOX_ADMIN_PASSWORD
        sync: false
      - key: FACEBOOK_PIXEL_ID
        sync: false
      - key: MUSIC_TRACKS
        value: funny_music.mp3,track1.mp3,track2.mp3,track3.mp3,track4.mp3
      - key: LEONARDO_API_KEY
        sync: false
      - key: REOON_API_KEY
        sync: false

services:
  - type: web
    name: liefeed
    runtime: docker
    plan: starter
    autoDeploy: true
    envVars:
      - fromGroup: shared-env

  - type: cron
    name: post-to-facebook
    runtime: docker
    plan: starter
    schedule: "0 */6 * * *"
    buildCommand: pip install -r requirements.txt
    envVars:
      - fromGroup: shared-env
      - key: RUN_TARGET
        value: post-to-facebook

  - type: cron
    name: send-newsletter
    runtime: docker
    plan: starter
    schedule: "0 10 * * 1,3,5"
    buildCommand: pip install -r requirements.txt
    envVars:
      - fromGroup: shared-env
      - key: RUN_TARGET
        value: send-newsletter

  - type: cron
    name: post-meme
    runtime: docker
    plan: starter
    schedule: "0 */12 * * *"
    buildCommand: pip install -r requirements.txt
    envVars:
      - fromGroup: shared-env
      - key: RUN_TARGET
        value: post-meme

  
  - type: cron
    name: post-reel-to-facebook
    runtime: docker
    plan: starter
    schedule: "30 10 * * *"
    buildCommand: pip install -r requirements.txt
    envVars:
      - fromGroup: shared-env
      - key: RUN_TARGET
        value: post-reel-to-facebook

  - type: cron
    name: validate-new-signups
    runtime: docker
    plan: starter
    schedule: "59 23 * * *"
    buildCommand: pip install -r requirements.txt
    envVars:
      - fromGroup: shared-env
      - key: RUN_TARGET
        value: validate-new-signups

  - type: cron
    name: trigger-daily-reel
    runtime: docker
    plan: starter
    schedule: "0 10 * * *"
    buildCommand: pip install -r requirements.txt
    envVars:
      - fromGroup: shared-env
      - key: RUN_TARGET
        value: trigger-daily-reel

