services:
  - type: web
    name: liefeed
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y libpango-1.0-0 libgdk-pixbuf2.0-0 libcairo2 libffi-dev && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
